import Profile from "./profile";
import AboutMe from "./aboutMe";
import TechStack from "./techStack";
import HelloWorld from "./helloWorld";
import Experience from "./experience";
import Social from "./Social";
import Education from "./education";
import Projects from "./projects";
export { Profile,AboutMe,TechStack,HelloWorld,Experience,Social,Education,Projects} ;